### ISSUE TITLE
Hot Spring Bonanza Sub-Quests

### ISSUE THREAD

**Issue by BLucidity** [r52/xc2-checklist#5]
Search for Tekuteku, Search for Alec, and Search for Sarrac are missing from the quest list. Technically completing Hot Spring Bonanza would encompass these, but with the sub-quests for defeating Brionac leaders and finding Dagas' past already included, I figured you'd want to add these as well.

By the way, yours is by far the best resource I've found for XC2 completionists. Thank you for creating it!

**Comment by r52** [comment]
Thanks. I haven't had the chance to play through the new DLC quests yet so I appreciate these reports.
